---

dict_k8s:
  one:
    name: atomic01
    ip: 192.168.56.91
  two:
    name: atomic02
    ip: 192.168.56.92
  three:
    name: atomic03
    ip: 192.168.56.93

mgmt_nodes:
  - name:  nucleus
    ip: 192.168.56.90

lb_name: haproxy
lb_ip: 192.168.56.91

flannel_name: 'vagrant'
flannel_internal_network: 172.16.0.0
flannel_network_prefix: 16
flannel_subnet_length: 24

internal_iface: 'enp0s8'
