---

- name: Deploy base configurations to mgmt node
  hosts: mgmt
  become: true
  become_user: root
  gather_facts: true
  vars_files:
    - "group_vars/{{ group_name }}.yml"  
  roles:
    - { role: base, tags: ['base'] }

- name: Deploy to k8s nodes
  hosts: k8s
  become: true
  become_user: root
  gather_facts: true
  vars_files:
    - "group_vars/{{ group_name }}.yml"  
  roles:
    - { role: base, tags: ['base'] }
    - { role: etcd, tags: ['etcd'] }
    - { role: flannel, tags: ['flannel'] }
    - { role: k8s-master, tags: ['k8s-master','master','k8s'] }
    - { role: k8s-worker, tags: ['k8s-worker','worker','k8s'] }
    - { role: kubectl, tags: ['kubectl','k8s'] }
    - { role: addons, tags: ['addons'] }
