---

- name: Create directory structure
  file:
    path: '{{ item }}'
    owner: root
    group: root
    state: directory
    mode: 0755
  with_items:
    - '{{ manifests_path }}'
  run_once: true
  when: "'{{ k8s_dict.instances[0].name }}' == inventory_hostname"

- name: Copy templates
  template:
    src: '{{ item }}.j2'
    dest: '{{ manifests_path }}/{{ item }}'
    owner: root
    group: root
    mode: 0664
  with_items:
    - 'kube-system.yaml'
    - 'kube-dns.yaml'
    - 'dashboard.yaml'
    - 'busybox.yaml'
  register: addons_copied
  run_once: true
  when: "'{{ k8s_dict.instances[0].name }}' == inventory_hostname"

- name: Deploy addons via kubectl
  script: deploy-addons.sh
  run_once: true
  ignore_errors: true
  when: ('{{ k8s_dict.instances[0].name }}' == inventory_hostname) and
        (addons_copied.changed)
