---

- name: Create directory structure
  file:
    path: '{{ item }}'
    owner: root
    group: root
    state: directory
    mode: 0755
  with_items:
    - '{{ manifests_path }}'
  run_once: true
  delegate_to: '{{ master_node }}'

- name: Copy templates
  template:
    src: '{{ item }}.j2'
    dest: '{{ manifests_path }}/{{ item }}'
    owner: root
    group: root
    mode: 0664
  with_items:
    - 'kube-system.yaml'
    - 'kube-dns.yaml'
    - 'dashboard.yaml'
    - 'busybox.yaml'
  run_once: true
  delegate_to: '{{ master_node }}'
